brick_detection:
  ros__parameters:
    google_drive_folder_url: "TODO"
    model_name: "best-int8_edgetpu.tflite"
    model_dir: "/home/budget_roomba_2/sven_space/ros_ws/src/br_brick_detection/br_brick_detection/model"
    yolov5_dir: "/home/budget_roomba_2/sven_space/pycoral/yolov5"
    pub_annotated_images: True
    input_image_topic: "/camera/image"
    output_image_topic: "/brick_detection/bounding_boxes/compressed"



